cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

language: android

jdk:
  - oraclejdk8

# todo: remove once https://github.com/travis-ci/travis-ci/issues/8874 is resolved
before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.2"

android:
  components:
    - tools
    - platform-tools

branches:
  only:
    - master

script: ./travis-build.sh
